// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmkfdoa3KrqUq4nPILciE08g03XU75VnM',
    appId: '1:990213572578:web:55a90c1ecf3f51d9dc9bbb',
    messagingSenderId: '990213572578',
    projectId: 'angular-flutter-cloud-2f167',
    authDomain: 'angular-flutter-cloud-2f167.firebaseapp.com',
    storageBucket: 'angular-flutter-cloud-2f167.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTTLTu0FaI2bcINIg_Zd5y7TNkZ616VrM',
    appId: '1:990213572578:android:c188ac2aca32c0cbdc9bbb',
    messagingSenderId: '990213572578',
    projectId: 'angular-flutter-cloud-2f167',
    storageBucket: 'angular-flutter-cloud-2f167.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ljoHeU3zKnCU5CUeykNBQul86sFURps',
    appId: '1:990213572578:ios:35bdbbf61842a230dc9bbb',
    messagingSenderId: '990213572578',
    projectId: 'angular-flutter-cloud-2f167',
    storageBucket: 'angular-flutter-cloud-2f167.firebasestorage.app',
    iosBundleId: 'com.example.todoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-ljoHeU3zKnCU5CUeykNBQul86sFURps',
    appId: '1:990213572578:ios:35bdbbf61842a230dc9bbb',
    messagingSenderId: '990213572578',
    projectId: 'angular-flutter-cloud-2f167',
    storageBucket: 'angular-flutter-cloud-2f167.firebasestorage.app',
    iosBundleId: 'com.example.todoMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmkfdoa3KrqUq4nPILciE08g03XU75VnM',
    appId: '1:990213572578:web:4bae3194154696bedc9bbb',
    messagingSenderId: '990213572578',
    projectId: 'angular-flutter-cloud-2f167',
    authDomain: 'angular-flutter-cloud-2f167.firebaseapp.com',
    storageBucket: 'angular-flutter-cloud-2f167.firebasestorage.app',
  );
}
